# __init__.py
colnames = ['YearMonthDayHourMinute','STN',
            'Lon','Lat','isitu-LST',
            'Band1','Band2','Band3','Band4','Band5', 'Band6',
            'Band7','Band8','Band9','Band10', 'Band11','Band12',
            'Band13','Band14','Band15','Band16',
            '30daysBand3','30daysBand13','GK2A-LST',
            'SolarZA','SateZA',
            'ESR','Height',
            'LandType',
            'insitu-TA','insitu-HM','insitu-TD','insitu-TG',
            'insitu-TED0.05','insitu-TED0.1','insitu-TED0.2',
            'insitu-TED0.3','insitu-TED0.5','insitu-TED1.0',
            'insitu-TED1.5','insitu-TED3.0','insitu-TED5.0',
            'insitu-PA','insitu-PS']

extract_col = ['YearMonthDayHourMinute',
               'isitu-LST', 'insitu-TG',
               'Band1', 'Band2', 'Band3',
               'Band4', 'Band6', 'Band7',
               'Band8', 'Band9', 'Band10', 'Band11',
               'Band12', 'Band13', 'Band14', 'Band15', 'Band16',
               '30daysBand3', '30daysBand13',
               'SolarZA', 'SateZA',
               'ESR', 'Height', 'LandType',
               'insitu-HM', 'insitu-TD']